services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.1
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/data
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/data/mlflow.db
      --default-artifact-root /mlflow/data/mlruns
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
    restart: always

  api:
    build: ./api
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ./feature_store:/app/feature_store
      - mlflow_data:/mlflow/data   

  trainer:
    build:
      context: .
      dockerfile: training/Dockerfile
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - .:/app
      - mlflow_data:/mlflow/data
    profiles:
      - training

volumes:
  mlflow_data: