FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow==2.22.0 psycopg2-binary

EXPOSE 5000

CMD mlflow server \
    --host 0.0.0.0 \
    --port 5000 \
    --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} \
    --default-artifact-root /mlflow/artifacts
